dist: xenial # needed to use python 3.7
language: python
branches:
  only:
    - master
python:
  - 3.7
cache: pip
before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests
install:
  - pip install -U pip
  - pip install travis-sphinx==2.2.1 nbsphinx==0.7.0 sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema
script: sphinx-build -nWT -b docs . build/html