language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true
      env:
        - DOCS="true"

install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests
  - pip install -U pip
  - pip install travis-sphinx==2.2.1 nbsphinx==0.7.0 sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema autoapi

script:
  # Use Sphinx to make the html docs
  - travis-sphinx build -n
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  - pip install travis-sphinx nbsphinx sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema
  - travis-sphinx build -n

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/source/