language: python

sudo: false
env:
  matrix:
    - DOCS="true"

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DOCS="true"

install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests
  - pip install -U pip
  - pip install travis-sphinx==2.2.1 nbsphinx==0.7.0 sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema

script:
  - if [[ "${DOCS}" == "true" ]]; then
      cd docs;
      make html;
    fi


deploy:
  # When commiting to master, auto-deploy to github-pages
  # This will copy the contents of the _build folder to gh-pages branch and push
- provider: pages
  edge: true
  local-dir: ./doc/build
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  on:
    # only do this when on the master branch
    branch: master