language: python

python:
  - 3.6
  - 3.7

install:
  - pip install .

script:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  - pip3 install travis-sphinx==2.2.1 nbsphinx sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema
  - travis-sphinx build -n
  - travis-sphinx deploy
