language: python

sudo: false
env:
  matrix:
    - DOCS="true"

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DOCS="true"

install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests
  - pip install -U pip
  - pip install travis-sphinx==2.2.1 nbsphinx==0.7.0 sphinx_rtd_theme jupyter_client ipykernel jupyter_sphinx sphinx-jsonschema

script:
  - if [[ "${DOCS}" == "true" ]]; then
      cd docs;
      make html;
    fi
deploy:
  provider: pages # deploy on github pages
  skip_cleanup: true
  github_token: "$GH_TOKEN" # defined via the Travis interface
  local_dir: ./docs/build/html